---
language: python
services: docker

env:
  global:
    - ROLE_NAME: nginx
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ansible-tomcat
  - cd tomcat

script:
  # Run tests.
  - molecule test

